const COMMENTS_RECIEVED_SUCCESS = "COMMENTS_RECIEVED_SUCCESS";
const COMMENTS_RECIEVED_FAILURE = "COMMENTS_RECIEVED_FAILURE";
const PODCAST_SEARCH_RECIEVED_SUCCESS = "PODCAST_SEARCH_RECIEVED_SUCCESS";
const PODCAST_SEARCH_RECIEVED_FAILURE = "PODCAST_SEARCH_RECIEVED_FAILURE";
const SEARCH_VALUE_CHANGED = "SEARCH_VALUE_CHANGED";
const AUDIO_PLAY = "AUDIO_PLAY";
const AUDIO_PAUSE = "AUDIO_PAUSE";
const AUDIO_INITIALIZED = "AUDIO_INITIALIZED";
const AUDIO_DURATION_SET = "AUDIO_DURATION_SET";
const TICK = "TICK";
const MOUSE_MOVE = "MOUSE_MOVE";
const MOUSE_UP = "MOUSE_UP";
const SCRUBBER_DOWN = "SCRUBBER_DOWN";
const SEARCH_RESULT_CLICKED = "SEARCH_RESULT_CLICKED";
const AUDIO_SRC_SET = "AUDIO_SRC_SET";
const PODCAST_RATINGS_RECIEVED = "PODCAST_RATINGS_RECIEVED";
const PODCAST_RATINGS_ERROR = "PODCAST_RATINGS_ERROR";


export { COMMENTS_RECIEVED_SUCCESS, COMMENTS_RECIEVED_FAILURE, PODCAST_SEARCH_RECIEVED_SUCCESS, PODCAST_SEARCH_RECIEVED_FAILURE, SEARCH_VALUE_CHANGED, AUDIO_PAUSE, AUDIO_PLAY, AUDIO_INITIALIZED, TICK, AUDIO_DURATION_SET, MOUSE_MOVE, MOUSE_UP, SCRUBBER_DOWN, SEARCH_RESULT_CLICKED, AUDIO_SRC_SET, PODCAST_RATINGS_RECIEVED, PODCAST_RATINGS_ERROR }