const COMMENTS_RECIEVED_SUCCESS = "COMMENTS_RECIEVED_SUCCESS";
const COMMENTS_RECIEVED_FAILURE= "COMMENTS_RECIEVED_FAILURE";
const AUDIO_PLAY= "AUDIO_PLAY";
const AUDIO_PAUSE= "AUDIO_PAUSE";
const AUDIO_INITIALIZED= "AUDIO_INITIALIZED";


export {COMMENTS_RECIEVED_SUCCESS, COMMENTS_RECIEVED_FAILURE,AUDIO_PAUSE,AUDIO_PLAY,AUDIO_INITIALIZED}