const COMMENTS_RECIEVED_SUCCESS = "COMMENTS_RECIEVED_SUCCESS";
const COMMENTS_RECIEVED_FAILURE= "COMMENTS_RECIEVED_FAILURE";
const AUDIO_PLAY= "AUDIO_PLAY";
const AUDIO_PAUSE= "AUDIO_PAUSE";
const AUDIO_INITIALIZED= "AUDIO_INITIALIZED";
const AUDIO_DURATION_SET = "AUDIO_DURATION_SET";
const TICK= "TICK";
const MOUSE_MOVE = "MOUSE_MOVE";
const MOUSE_UP = "MOUSE_UP";
const SCRUBBER_DOWN = "SCRUBBER_DOWN";


export {COMMENTS_RECIEVED_SUCCESS, COMMENTS_RECIEVED_FAILURE,AUDIO_PAUSE,AUDIO_PLAY,AUDIO_INITIALIZED,TICK, AUDIO_DURATION_SET,MOUSE_MOVE,MOUSE_UP,SCRUBBER_DOWN}